spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    url: jdbc:mysql://pre-stackoverflow.cfw9bxmlnyty.ap-northeast-2.rds.amazonaws.com:13306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: pre35000
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: http://pre-stackoverflow.s3-website.ap-northeast-2.amazonaws.com
#    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: test123123123123123123123123123123123123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG
#server:
#  servlet:
#    encoding:
#      force-response: true
